[project]
name = "storage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "f-braud-ece", email = "frank.braud@edu.ece.fr" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
storage = "storage:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
